---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Including Code

Headline Results

```{r load, echo=FALSE}
library(sf)
library(tmap)
library(dplyr)
library(countrycode)
library(tidyr)
library(ggplot2)
library(furrr)

pass_od <- read_sf("../../data/clean/od_emissions_2021.gpkg")
airports <- read_sf("../../data/clean/airports_clean_second_pass_2021.gpkg")




pass_inter <- st_drop_geometry(pass_od)
pass_inter <- pass_inter[pass_inter$airport2_country != "United Kingdom", ]
pass_inter <- pass_inter[!is.na(pass_inter$pass_2019),]
pass_inter <- pass_inter[pass_inter$pass_2019 > 0,]
# Get Flight Distance

pass_inter <- group_by(pass_inter, airport2, airport2_country) %>%
  summarise(pass_2019 = sum(pass_2019, na.rm = T),
            pass_km_2019 = sum(pass_km_2019, na.rm = T),
            emissions_2019 = sum(emissions_2019, na.rm = T),
            pass_2020 = sum(pass_2020, na.rm = T),
            pass_km_2020 = sum(pass_km_2020, na.rm = T),
            emissions_2020 = sum(emissions_2020, na.rm = T),
            pass_2021 = sum(pass_2021, na.rm = T),
            pass_km_2021 = sum(pass_km_2021, na.rm = T),
            emissions_2021 = sum(emissions_2021, na.rm = T))

pass_inter <- pass_inter[pass_inter$pass_2019 > 0,]
pass_inter <- pass_inter[pass_inter$airport2 != "Unknown",]
summary(pass_inter$airport2 %in% airports$airport)

pass_inter <- left_join(airports, pass_inter, by = c("airport" = "airport2", "country" = "airport2_country"))
pass_inter <- pass_inter[!is.na(pass_inter$pass_2019),]
pass_inter <- pass_inter[pass_inter$pass_2019 > 0,]


```

## International Passengers

```{r int_pass, echo=FALSE}

data(World)
World <- st_transform(World, 4326)
m1 <- tm_shape(pass_inter) +
  tm_bubbles(size = "pass_2019", 
             title.size = "Passengers 2019",
             col = "green") +
  tm_shape(World) +
  tm_borders(col = "black") +
  tm_layout(legend.position = c("left","bottom"))
tmap_save(m1, filename = "../../plots/international_passengers.png")

m2 <- tm_shape(pass_inter) +
  tm_bubbles(size = "pass_km_2019", 
             title.size = "Passenger Kilometres 2019",
             col = "blue") +
  tm_shape(World) +
  tm_borders(col = "black") +
  tm_layout(legend.position = c("left","bottom"))
tmap_save(m2, filename = "../../plots/international_passengers_km.png")

txt = expression("Emissions (kgCO"[2]~"e) 2019")
m3 <- tm_shape(pass_inter) +
  tm_bubbles(size = "emissions_2019", 
             title.size = txt,
             col = "red") +
  tm_shape(World) +
  tm_borders(col = "black") +
  tm_layout(legend.position = c("left","bottom"))
tmap_save(m3, filename = "../../plots/international_emissions.png")
```


## International Passengers By Country/Region

```{r int_pass_pie, echo=FALSE}

pass_region <- st_drop_geometry(pass_od)
pass_region <- pass_region %>%
  group_by(country_region) %>%
  summarise(pass_2019 = sum(pass_2019, na.rm = TRUE),
            pass_km_2019 = sum(pass_km_2019, na.rm = TRUE),
            emissions = sum(emissions_2019, na.rm = TRUE))

pass_region$country_region <- factor(pass_region$country_region, levels = c("Domestic","Spain", "Italy", "Germany", "France", "Ireland","Netherlands","Portugal","Poland", "Greece", "Turkey","Europe Other","USA","Canada","Americas Other","UAE","India","Hong Kong","Singapore", "Asia Other", "Africa","Oceania"))
                      

```


```{r sankey}

if(FALSE){
  library(ggsankey)  
  
  df <- as.data.frame(pass_region)
  row.names(df) <- df$country_region
  df$country_region <- NULL
  df$pass_2019 <- df$pass_2019 / max(df$pass_2019) * 100
  df$pass_km_2019 <- df$pass_km_2019 / max(df$pass_km_2019) * 100
  df$emissions <- df$emissions / max(df$emissions) * 100
  
  df2 <- df %>%
  make_long(pass_2019,pass_km_2019,emissions)
  
  
  foo <- mtcars %>%
  make_long(cyl, vs, am, gear, carb)
  
  ggplot(foo, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey()

  
  ggplot(df2, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(x))) +
  geom_sankey(flow.alpha = .6)
  
  
  ggplot(pass_region, aes(node=name, x=value,
                        fill = country_region)) +
  geom_sankey() +
  labs(fill = "Country or Region")
  
}



```


```{r int_pass_pie_plot, echo=FALSE}
pass_region <- pivot_longer(pass_region, cols = c("pass_2019", "pass_km_2019", "emissions"))
pass_region$name <- factor(pass_region$name, levels = c("pass_2019", "pass_km_2019", "emissions"))
ggplot(pass_region, aes(x=name, y=value, fill = country_region)) +
  geom_col(position = "fill", colour="black") +
  coord_polar("y", start=0) +
  scale_x_discrete(labels = c("Passengers", "Passenger km", "Emissions")) +
  theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank(),
       axis.title.y=element_blank(),
       axis.text.y=element_blank(),
       axis.ticks.y=element_blank(),
       panel.grid.minor = element_blank(),
       panel.background = element_blank(),
       axis.line = element_blank()) +
  scale_fill_manual(values=c("#4d4d4d","#a50026","#d73027","#f46d43","#fdae61","#fee090",
                             "#ffffbf","#e0f3f8","#abd9e9","#74add1","#4575b4",
                             "#313695",
                             "#2ca25f","#99d8c9","#e5f5f9",
                             "#810f7c","#8856a7","#8c96c6","#9ebcda",
                             "#bfd3e6",
                             "#f4cae4",
                             "#e6f5c9")) +
  labs(fill = "Country or Region")
  ggsave("../../plots/passengers_and_km_pie.png", dpi = 600)
  
  
ggplot(pass_region, aes(x=name, y=value, fill = country_region)) +
  geom_col(position = "fill", colour="black") +
  scale_x_discrete(labels = c("Passengers", "Passenger km", "Emissions")) +
  theme(axis.title.x=element_blank(),
       axis.ticks.x=element_blank(),
       axis.title.y=element_blank(),
       axis.text.y=element_blank(),
       axis.ticks.y=element_blank(),
       panel.grid.minor = element_blank(),
       panel.background = element_blank(),
       axis.line = element_blank()) +
  scale_fill_manual(values=c("#4d4d4d","#a50026","#d73027","#f46d43","#fdae61","#fee090",
                             "#ffffbf","#e0f3f8","#abd9e9","#74add1","#4575b4",
                             "#313695",
                             "#2ca25f","#99d8c9","#e5f5f9",
                             "#810f7c","#8856a7","#8c96c6","#9ebcda",
                             "#bfd3e6",
                             "#f4cae4",
                             "#e6f5c9")) +
  guides(fill=guide_legend(ncol =1)) +
  labs(fill = "Country or Region")
  ggsave("../../plots/passengers_and_km_bar_2.png", dpi = 600)

#pass_region$order <- paste0(pass_region$country_region," ",pass_region$name)
pass_region <- pass_region[order(pass_region$name, pass_region$value),]
pass_region$ordering <- rep(1:22, 3)
pass_region$name2 <- rep(c("A","B","C"), each = 22)

ggplot(pass_region, aes(x=name2, y=value, 
                        fill = reorder(country_region,-ordering))) +
  geom_col(position = "fill", colour="black", data = pass_region %>% filter(name == "pass_2019")) +
  geom_col(position = "fill", colour="black", data = pass_region %>% filter(name == "pass_km_2019")) +
  geom_col(position = "fill", colour="black", data = pass_region %>% filter(name == "emissions")) +
  guides(fill=guide_legend("ordering")) +
  #scale_x_discrete(limits = pass_region$order) +
  #coord_polar("y", start=0) +
  scale_x_discrete(labels = c("Passengers", "Passenger km", "Emissions")) +
  theme(
    
       axis.title.x=element_blank(),
       axis.ticks.x=element_blank(),
       axis.title.y=element_blank(),
       axis.text.y=element_blank(),
       axis.ticks.y=element_blank(),
       panel.grid.minor = element_blank(),
       panel.background = element_blank(),
       axis.line = element_blank()) +
  scale_fill_manual(values=c('#a50026','#313695','#2ca25f','#4d4d4d','#d73027',
                             '#bfd3e6','#f46d43','#fdae61','#fee090','#ffffbf',
                             '#e0f3f8','#abd9e9','#74add1','#810f7c','#f4cae4',
                             '#4575b4','#e5f5f9','#99d8c9','#8856a7','#8c96c6',
                             '#9ebcda','#e6f5c9')) +
  labs(fill = "Country or Region")
  ggsave("../../plots/passengers_and_km_bar_sort.png", dpi = 600)
  
```

# Total international passengers per year destination
```{r flights_per_year, echo=FALSE}
pass_cont <- st_drop_geometry(pass_od)

pass_cont = pass_cont[,c("country_region",
                         paste0("pass_",as.character(1990:2021)),
                         paste0("pass_km_",as.character(1990:2021)),
                         paste0("emissions_",as.character(1990:2021)))]
names(pass_cont) = c("country_region",
                         paste0("pass_",as.character(1990:2021)),
                         paste0("passkm_",as.character(1990:2021)),
                         paste0("emissions_",as.character(1990:2021)))

pass_cont = pass_cont %>%
  group_by(country_region) %>%
  summarise_all(sum, na.rm = TRUE)

pass_cont = pivot_longer(pass_cont, cols = !country_region,
                         names_to = c(".value","year"),
                         names_pattern = "([^\\.]*)\\_*(\\d{4})",
                         values_to = "total")
# names(pass_cont) = c("country_region","year","passengers" )

pass_cont$year <- as.integer(pass_cont$year)
pass_cont$country_region <- factor(pass_cont$country_region, 
                           levels = c("Domestic","Spain","Italy","Germany","France","Ireland",
                                     "Netherlands","Portugal","Poland","Greece","Turkey",
                                     "Europe Other",
                                     "USA","Canada","Americas Other",
                                     "UAE","India","Hong Kong","Singapore",
                                     "Asia Other",
                                     "Oceania",
                                     "Africa"))


ggplot(pass_cont, aes(x = year, y = pass_, fill = country_region)) +
  geom_area() +
  scale_fill_manual(values=c("#4d4d4d","#a50026","#d73027","#f46d43","#fdae61","#fee090",
                             "#ffffbf","#e0f3f8","#abd9e9","#74add1","#4575b4",
                             "#313695",
                             "#2ca25f","#99d8c9","#e5f5f9",
                             "#810f7c","#8856a7","#8c96c6","#9ebcda",
                             "#bfd3e6",
                             "#e6f5c9",
                             "#f4cae4")) +
  scale_y_continuous(labels = scales::unit_format(unit = "Mln", scale = 1e-6),
                     expand = c(0, 0)) +
  labs(fill = "Country or Region") +
  ylab("Passengers") +
  xlab("Year") +
  theme(legend.text = element_text(size=6),
        legend.key.size = unit(0.6, 'line'),
        legend.title = element_text(size=8)) +
  guides(fill = guide_legend(ncol = 1)) +
  scale_x_continuous(expand = c(0, 0), breaks = seq(1990,2021,2))
  ggsave("../../plots/passengers_per_year.png", dpi = 600, width = 8, height = 4)
  
 
ggplot(pass_cont, aes(x = year, y = passkm_, fill = country_region)) +
  geom_area() +
  scale_fill_manual(values=c("#4d4d4d","#a50026","#d73027","#f46d43","#fdae61","#fee090",
                             "#ffffbf","#e0f3f8","#abd9e9","#74add1","#4575b4",
                             "#313695",
                             "#2ca25f","#99d8c9","#e5f5f9",
                             "#810f7c","#8856a7","#8c96c6","#9ebcda",
                             "#bfd3e6",
                             "#e6f5c9",
                             "#f4cae4")) +
  scale_y_continuous(labels = scales::unit_format(unit = "Bln", scale = 1e-9),
                     expand = c(0, 0)) +
  labs(fill = "Country or Region") +
  ylab("Passengers km") +
  xlab("Year") +
  theme(legend.text = element_text(size=6),
        legend.key.size = unit(0.6, 'line'),
        legend.title = element_text(size=8)) +
  guides(fill = guide_legend(ncol = 1)) +
  scale_x_continuous(expand = c(0, 0), breaks = seq(1990,2021,2))
  ggsave("../../plots/passenger_km_per_year.png", dpi = 600, width = 8, height = 4)

txt = expression("Emissions (kgCO"[2]~"e)") 
ggplot(pass_cont, aes(x = year, y = emissions_, fill = country_region)) +
  geom_area() +
  scale_fill_manual(values=c("#4d4d4d","#a50026","#d73027","#f46d43","#fdae61","#fee090",
                             "#ffffbf","#e0f3f8","#abd9e9","#74add1","#4575b4",
                             "#313695",
                             "#2ca25f","#99d8c9","#e5f5f9",
                             "#810f7c","#8856a7","#8c96c6","#9ebcda",
                             "#bfd3e6",
                             "#e6f5c9",
                             "#f4cae4")) +
  scale_y_continuous(labels = scales::unit_format(unit = "Bln", scale = 1e-9),
                     expand = c(0, 0)) +
  labs(fill = "Country or Region") +
  ylab(txt) +
  xlab("Year") +
  theme(legend.text = element_text(size=6),
        legend.key.size = unit(0.6, 'line'),
        legend.title = element_text(size=8)) +
  guides(fill = guide_legend(ncol = 1)) +
  scale_x_continuous(expand = c(0, 0), breaks = seq(1990,2021,2))
  ggsave("../../plots/emissions_per_year.png", dpi = 600, width = 8, height = 4)


```





```{r eu_bounds, echo=FALSE}
dir.create("tmp")
unzip("../../data/Europe Bounds/ref-countries-2020-20m.geojson.zip", exdir = "tmp")
bounds <- read_sf("tmp/CNTR_BN_20M_2020_4326.geojson")
unlink("tmp", recursive = TRUE)
```


## Doemstic and Near based OD

```{r int_pass, echo=FALSE}
od_near <- pass_od[pass_od$length_km < 4000,]
od_near <- od_near[!is.na(od_near$pass_2019),]
od_near <- od_near[od_near$pass_2019> 10000,]
od_near <- od_near[order(od_near$pass_2019),]

box <- st_bbox(od_near)
box[1] <- -30
box <- st_as_sfc(box, )
box <- st_as_sf(box)

m5 <- tm_shape(box) +
  tm_fill(alpha = 0) +
  tm_shape(od_near) +
  tm_lines(col = "pass_2019", 
           lwd = "pass_2019",
           title.col = "Passengers (2019)",
           legend.lwd.show = FALSE,
           style = "fixed",
           breaks = c(10000,50000,100000,200000,500000,1000000,2000000),
           scale = 3,
           palette = viridisLite::plasma(10, end = 0.31, begin = 0.95)
            ) +
  tm_shape(bounds) +
  tm_lines(col = "black") +
  tm_shape(airports[airports$airport %in% od_near$airport1 | airports$airport %in% od_near$airport2,]) +
  tm_dots(col = "black") +
  tm_legend(position = c(0.78,0.8)) +
  tm_compass(position = c("left","bottom")) +
  tm_scale_bar(position = c("right","bottom")) +
  tm_layout(legend.bg.color = "white",
            legend.bg.alpha = 0.7)

od_bi <- od_near[od_near$length_km < 755,]
od_bi <- od_bi[od_bi$airport2_country %in% c("United Kingdom","Irish Republic","Isle of Man","Jersey"),]

m5b <- tm_shape(od_bi) +
  tm_lines(col = "pass_2019", 
           lwd = "pass_2019",
           title.col = "Passengers (2019)",
           legend.lwd.show = FALSE,
           legend.col.show = FALSE,
           style = "fixed",
           breaks = c(10000,50000,100000,200000,500000,1000000,2000000),
           scale = 3,
           palette = viridisLite::plasma(10, end = 0.31, begin = 0.95)
            ) +
  tm_shape(bounds) +
  tm_lines(col = "black") +
  tm_shape(airports[airports$airport %in% od_bi$airport1 | airports$airport %in% od_bi$airport2,]) +
  tm_dots(col = "black") +
  tm_scale_bar(position = c("right","top"), breaks = c(0,100,200))


xy <- st_bbox(od_near)
asp2 <- (xy$xmax - xy$xmin)/(xy$ymax - xy$ymin)

w <- 0.34
h <- asp2 * w
vp <- grid::viewport(x=0.32, y=0.99, width = w, height=h, just=c("right", "top"))

  
tmap_save(m5, insets_tm=m5b, insets_vp=vp, filename = "../../plots/near_OD5_inset.png")

```

## All OD

```{r int_pass, echo=FALSE}
od_all <- pass_od
od_all <- od_all[!is.na(od_all$pass_2019),]
od_all <- od_all[od_all$pass_2019> 0,]
od_all <- od_all[order(od_all$pass_2019),]

m6 <- tm_shape(od_all) +
  tm_lines(col = "pass_2019", 
           lwd = "pass_2019",
           title.col = "Passengers (2019)",
           legend.lwd.show = FALSE,
           style = "jenks",
           n = 10,
           scale = 3,
           palette = viridisLite::plasma(10, end = 0.31, begin = 0.95)
            ) +
  tm_shape(bounds) +
  tm_lines(col = "black") +
  tm_shape(airports[airports$airport %in% od_all$airport1 | airports$airport %in% od_all$airport2,]) +
  tm_dots(col = "black") +
  tm_legend(position = c(0.01,0.05)) +
  tm_compass(position = c("left","top")) +
  tm_scale_bar(position = c("right","top"))
  
tmap_save(m6, filename = "../../plots/all_OD.png")

```



## Top routes over time

```{r top_routes, echo=FALSE}
od <- read_sf("../../data/clean/od_flights_pass_v2.gpkg")
od$route <- paste0(od$airport1," to ",od$airport2)
od <- st_drop_geometry(od)

rts <- ""
for(i in 1990:2018){
  od <- od[order(od[paste0("X",i)], decreasing = TRUE),]
  rts <- c(rts, od$route[1:10])
}

rts <- unique(rts)
rts <- rts[rts != ""]
od_top <- od[od$route %in% rts, ]

od_top <- od_top[,c("route", paste0("X",1990:2018))]


od_top <- pivot_longer(od_top, cols = starts_with("X"))
names(od_top) <- c("route","year","passengers")
od_top$year <- as.numeric(gsub("X","",od_top$year))

od_top <- od_top[od_top$passengers != 0,]

# ggplot(od_top, aes(x = year, y = passengers, color = route)) +
#   geom_line() +
#   geom_point() +
#   scale_y_continuous(labels = paste0(seq(0,4,0.5), "M"),
#                      breaks = 10^6 * seq(0,4,0.5)
#   ) +
#   # Add labels at the end of the line
#   geom_text(data = filter(od_top, year == max(year)),
#             aes(label = route),
#             hjust = 0, nudge_x = 0.1) +
#   # Allow labels to bleed past the canvas boundaries
#   coord_cartesian(clip = 'off') +
#   # Remove legend & adjust margins to give more space for labels
#   # Remember, the margins are t-r-b-l
#   theme(legend.position = 'none',
#         plot.margin = margin(0.1, 6.2, 0.1, 0.1, "cm")) +
#   ggsave("top_10_routes_2018.png", width = 6, height = 10)


ggplot(od_top, aes(x = year, y = passengers, color = route)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = paste0(seq(0,4,1), "M"),
                     breaks = 10^6 * seq(0,4,1)
  ) +
  facet_wrap(vars(route), labeller = label_wrap_gen(width=30)) +
  theme(legend.position = "none",
        strip.text = element_text(size=5)) +
  ggsave("top_10_routes_2018.png", width = 6, height = 8)

```
## Cluster Airports

```{r cluster_airports, echo=FALSE}
library(geosphere)
#airports <- read_sf("../../data/clean/airports_clean_second_pass_v2.gpkg")
airports <- as(airports,"Spatial")
# use the distm function to generate a geodesic distance matrix in meters
mdist <- distm(airports)
# cluster all points using a hierarchical clustering approach
hc <- hclust(as.dist(mdist), method="complete")
# define the distance threshold, in this case 90 km
d=90000
# define clusters based on a tree "height" cutoff "d" and add them to the SpDataFrame
airports$clust <- cutree(hc, h=d)
airports <- st_as_sf(airports)

airports$clust <- as.character(airports$clust)


tm_shape(airports[airports$clust %in% airports$clust[duplicated(airports$clust)],]) +
  tm_dots(col = "clust")

airports_jn <- st_drop_geometry(airports)
names(airports_jn) <- c("airport","country","clust_from")
od <- left_join(pass_od, airports_jn, by = c("airport1" = "airport", "airport1_country" = "country"))
names(airports_jn) <- c("airport","country","clust_to")
od <- left_join(od, airports_jn, by = c("airport2" = "airport", "airport2_country" = "country"))
od$route <- paste0(od$airport1," to ",od$airport2)
od <- st_drop_geometry(od)

od_clust <- od %>%
  select(-airport1, -airport1_country, -airport2, -airport2_country, -route,
         -length_km, -continent, -length_km_detour, -country_region, -distance_band) %>%
  group_by(clust_from, clust_to) %>%
  summarise_all(sum, na.rm = TRUE)

od_clust$route <- paste0(od_clust$clust_from," to ",od_clust$clust_to)
od_clust <- as.data.frame(od_clust)

rts <- ""
for(i in 1990:2021){
  od_clust <- od_clust[order(od_clust[,paste0("pass_",i)], decreasing = TRUE),]
  rts <- c(rts, od_clust$route[1:10])
}

rts <- unique(rts)
rts <- rts[rts != ""]
od_clus_top <- od_clust[od_clust$route %in% rts, ]
# qtm(airports[airports$clust %in% od_clus_top$clust_from | 
#                airports$clust %in% od_clus_top$clust_to,])

od_clus_top <- od_clus_top[,c("route", paste0("pass_",1990:2021))]


od_clus_top$route <- gsub("\\b694\\b","London",od_clus_top$route)
od_clus_top$route <- gsub("\\b60\\b","Dublin",od_clus_top$route)
od_clus_top$route <- gsub("\\b689\\b","Edinburgh",od_clus_top$route)
od_clus_top$route <- gsub("\\b85\\b","Amsterdam/Rotterdam",od_clus_top$route)
od_clus_top$route <- gsub("\\b685\\b","Belfast",od_clus_top$route)
od_clus_top$route <- gsub("\\b258\\b","New York",od_clus_top$route)
od_clus_top$route <- gsub("\\b167\\b","Dubai",od_clus_top$route)
od_clus_top$route <- gsub("\\b690\\b","Glasgow",od_clus_top$route)
od_clus_top$route <- gsub("\\b87\\b","Barcelona",od_clus_top$route)
od_clus_top$route <- gsub("\\b93\\b","Madrid",od_clus_top$route)
od_clus_top$route <- gsub("\\b22\\b","Geneva",od_clus_top$route)
od_clus_top$route <- gsub("\\b78\\b","Rome",od_clus_top$route)
od_clus_top$route <- gsub("\\b90\\b","Malaga/Granada",od_clus_top$route)
od_clus_top$route <- gsub("\\b34\\b","Paris",od_clus_top$route)
od_clus_top$route <- gsub("\\b47\\b","Frankfurt/Mannheim",od_clus_top$route)
od_clus_top$route <- gsub("\\b202\\b","Los Angeles",od_clus_top$route)
od_clus_top$route <- gsub("\\b120\\b","Zurich",od_clus_top$route)
od_clus_top$route <- gsub("\\b695\\b","Manchester/Liverpool",od_clus_top$route)
od_clus_top$route <- gsub("\\b7\\b","Brussels/Antwerp",od_clus_top$route)
od_clus_top$route <- gsub("\\b67\\b","Milan",od_clus_top$route)
od_clus_top$route <- gsub("\\b728\\b","Lisbon",od_clus_top$route)
od_clus_top$route <- gsub("\\b124\\b","Istanbul",od_clus_top$route)

table(od_clus_top$route)

od_clus_top <- pivot_longer(od_clus_top, cols = starts_with("pass_"))
names(od_clus_top) <- c("route","year","passengers")
od_clus_top$year <- as.numeric(gsub("pass_","",od_clus_top$year))
od_clus_top <- od_clus_top[od_clus_top$passengers != 0,]

od_clus_top <- od_clus_top[od_clus_top$route != "London to Zurich",] # One too many for nice plot
od_clus_top$route <- gsub(" to London","",od_clus_top$route)
od_clus_top$route <- gsub("London to","",od_clus_top$route)
od_clus_top$route <- trimws(od_clus_top$route)
od_clus_top <- od_clus_top[order(od_clus_top$route),]


ggplot(od_clus_top, aes(x = year, y = passengers, color = route)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = paste0(seq(0,8,2), "M"),
                     breaks = 10^6 * seq(0,8,2)
  ) +
  facet_wrap(vars(route), labeller = label_wrap_gen(width=30), ncol = 4) +
  theme(legend.position = "none",
        strip.text = element_text(size=6),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("Year") +
  ylab("Passengers")
  ggsave("../../plots/top_10_routes_clusters_2021b.png", width = 6, height = 8)

```

## Top clusters for passenger km


```{r cluster_airports_km, echo=FALSE}

od_clust$pass_km_1990 <- od_clust$X1990 * od_clust$length_km
od_clust$pass_km_1991 <- od_clust$X1991 * od_clust$length_km
od_clust$pass_km_1992 <- od_clust$X1992 * od_clust$length_km
od_clust$pass_km_1993 <- od_clust$X1993 * od_clust$length_km
od_clust$pass_km_1994 <- od_clust$X1994 * od_clust$length_km
od_clust$pass_km_1995 <- od_clust$X1995 * od_clust$length_km
od_clust$pass_km_1996 <- od_clust$X1996 * od_clust$length_km
od_clust$pass_km_1997 <- od_clust$X1997 * od_clust$length_km
od_clust$pass_km_1998 <- od_clust$X1998 * od_clust$length_km
od_clust$pass_km_1999 <- od_clust$X1999 * od_clust$length_km
od_clust$pass_km_2000 <- od_clust$X2000 * od_clust$length_km
od_clust$pass_km_2001 <- od_clust$X2001 * od_clust$length_km
od_clust$pass_km_2002 <- od_clust$X2002 * od_clust$length_km
od_clust$pass_km_2003 <- od_clust$X2003 * od_clust$length_km
od_clust$pass_km_2004 <- od_clust$X2004 * od_clust$length_km
od_clust$pass_km_2005 <- od_clust$X2005 * od_clust$length_km
od_clust$pass_km_2006 <- od_clust$X2006 * od_clust$length_km
od_clust$pass_km_2007 <- od_clust$X2007 * od_clust$length_km
od_clust$pass_km_2008 <- od_clust$X2008 * od_clust$length_km
od_clust$pass_km_2009 <- od_clust$X2009 * od_clust$length_km
od_clust$pass_km_2010 <- od_clust$X2010 * od_clust$length_km
od_clust$pass_km_2011 <- od_clust$X2011 * od_clust$length_km
od_clust$pass_km_2012 <- od_clust$X2012 * od_clust$length_km
od_clust$pass_km_2013 <- od_clust$X2013 * od_clust$length_km
od_clust$pass_km_2014 <- od_clust$X2014 * od_clust$length_km
od_clust$pass_km_2015 <- od_clust$X2015 * od_clust$length_km
od_clust$pass_km_2016 <- od_clust$X2016 * od_clust$length_km
od_clust$pass_km_2017 <- od_clust$X2017 * od_clust$length_km
od_clust$pass_km_2018 <- od_clust$X2018 * od_clust$length_km


rts <- ""
for(i in 1990:2018){
  od_clust <- od_clust[order(od_clust[paste0("pass_km_",i)], decreasing = TRUE),]
  rts <- c(rts, od_clust$route[1:10])
}

rts <- unique(rts)
rts <- rts[rts != ""]
od_clus_top <- od_clust[od_clust$route %in% rts, ]
od_clus_top <- od_clus_top[,c("route", paste0("pass_km_",1990:2018))]

#qtm(airports[airports$clust == 192,])

od_clus_top$route <- gsub("687","London",od_clus_top$route)
od_clus_top$route <- gsub("257","New York",od_clus_top$route)
od_clus_top$route <- gsub("166","Dubai",od_clus_top$route)
od_clus_top$route <- gsub("201","Los Angeles",od_clus_top$route)
od_clus_top$route <- gsub("176","Hong Kong/Shenzhen",od_clus_top$route)
od_clus_top$route <- gsub("179","Singapore",od_clus_top$route)
od_clus_top$route <- gsub("207","San Francisco",od_clus_top$route)
od_clus_top$route <- gsub("187","Toronto",od_clus_top$route)
od_clus_top$route <- gsub("198","Miami",od_clus_top$route)
od_clus_top$route <- gsub("159","Johannesburg",od_clus_top$route)
od_clus_top$route <- gsub("194","Chicago",od_clus_top$route)
od_clus_top$route <- gsub("294","Doha",od_clus_top$route)
od_clus_top$route <- gsub("177","Tokyo",od_clus_top$route)
od_clus_top$route <- gsub("203","Orlando",od_clus_top$route)
od_clus_top$route <- gsub("191","Washington/Baltimore",od_clus_top$route)
od_clus_top$route <- gsub("192","Boston/Providence",od_clus_top$route)
od_clus_top$route <- gsub("33","Paris",od_clus_top$route)


od_clus_top <- pivot_longer(od_clus_top, cols = starts_with("pass_km_"))
names(od_clus_top) <- c("route","year","passenger_km")
od_clus_top$year <- as.numeric(gsub("pass_km_","",od_clus_top$year))
od_clus_top <- od_clus_top[od_clus_top$passenger_km != 0,]

ggplot(od_clus_top, aes(x = year, y = passenger_km, color = route)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = paste0(seq(0,600,200), "B"),
                     breaks = 10^9 * seq(0,600,200)
  ) +
  facet_wrap(vars(route), labeller = label_wrap_gen(width=30)) +
  ylab("Passenger km") +
  theme(legend.position = "none",
        strip.text = element_text(size=5)) +
  ggsave("top_10_routes_km_clusters.png", width = 6, height = 8)

```



## European Flights vs Rail

```{r int_pass, echo=FALSE}

pass_europe <- pass_inter
pass_europe$continent <- countrycode(sourcevar = pass_europe$country,
                            origin = "country.name",
                            destination = "continent")
pass_europe$continent[pass_europe$country == "Irish Republic"] <- "Europe"
pass_europe$continent[pass_europe$country == "Kosovo"] <- "Europe"
pass_europe$continent[pass_europe$country == "Oil Rigs"] <- "Europe"
pass_europe <- pass_europe[pass_europe$continent == "Europe",]




```

```{r int_pass_plot, echo=FALSE}
if(FALSE){
  rail <- read_sf("../../data/europe-rail-highspeed.gpkg")
rail$maxspeed <- as.numeric(rail$maxspeed)
rail$maxspeed[rail$maxspeed > 400] <- NA
rail <- rail[!is.na(rail$maxspeed),]
rail <- rail[rail$maxspeed > 100,]

m3 <- tm_shape(rail) +
  tm_lines(col = "maxspeed", 
           lwd = 2,
           title.col = "Line speed (kph)") +
  tm_shape(pass_europe) +
  tm_bubbles(size = "pass_2018", 
             title.size = "UK passengers (2018)",
             col = "blue") +
  tm_shape(bounds) +
  tm_lines(col = "black") +
  tm_layout(legend.position = c("left","top"),
            legend.bg.color = "white")
tmap_save(m3, filename = "international_passengers_europe.png")
}


```


## Spanish Islands

```{r int_pass, echo=FALSE}

pass_spain <- pass_europe[pass_europe$country == "Spain",] 
balearic_islands <- c("Ibiza","Palma De Mallorca","Menorca")
canary_islands <- c("Arrecife","Fuerteventura","Las Palmas","Tenerife (Surreina Sofia)","Tenerife (Norte Los Rodeos)","Santa Cruz De La Palma")

pass_spain$balearic_islands <- pass_spain$airport %in% balearic_islands
pass_spain$canary_islands <- pass_spain$airport %in% canary_islands

sum(pass_spain$pass_2018[pass_spain$balearic_islands]) / sum(pass_spain$pass_2018)
sum(pass_spain$pass_2018[pass_spain$canary_islands]) / sum(pass_spain$pass_2018)

sum(pass_spain$pass_km_2018[pass_spain$balearic_islands]) / sum(pass_spain$pass_km_2018)
sum(pass_spain$pass_km_2018[pass_spain$canary_islands]) / sum(pass_spain$pass_km_2018)

sum(pass_spain$pass_km_2018[!pass_spain$balearic_islands & !pass_spain$canary_islands]) / sum(pass_inter$pass_km_2018[pass_inter$country == "Italy"])

```


## Main Rail Routes

```{r int_pass, echo=FALSE}

main_rail <- read_sf("../../data/main_rail.gpkg")
main_rail$length_km <- as.numeric(st_length(main_rail)) / 1000
main_rail$speed_kph <- main_rail$length_km / (main_rail$time_min / 60)
main_rail$proposed[is.na(main_rail$proposed)] <- "FASLE"
main_rail$proposed[main_rail$proposed %in% c("FLASE","FASLE")]  <- "FASLE"
rail_buff <- st_buffer(st_transform(main_rail[main_rail$proposed == "FALSE",], 3035), units::as_units(50, "kilometres"))
rail_buff <- st_union(rail_buff)
rail_buff <- st_transform(rail_buff, 4326)

m4 <- tm_shape(main_rail[main_rail$proposed == "FALSE",]) +
  tm_lines(col = "speed_kph", 
           lwd = 2,
           title.col = "Average speed (kph)") +
  tm_shape(pass_europe) +
  tm_bubbles(size = "pass_2018", 
             title.size = "UK passengers (2018)",
             col = "blue") +
  tm_shape(bounds) +
  tm_lines(col = "black") +
  tm_shape(rail_buff) +
  tm_borders(col = "red") +
  tm_layout(legend.position = c("left","top"),
            legend.bg.color = "white",
            legend.stack = "horizontal") 
tmap_save(m4, filename = "international_passengers_europe_main_rail.png")

# In the study area
in_study <- st_intersects(airports, rail_buff)
in_study <- lengths(in_study) > 0
airports$in_study <- in_study

airports_instudy <- st_drop_geometry(airports)
names(airports_instudy) <- c("airport", "country", "in_study_1")

pass_od <- left_join(pass_od, airports_instudy, by = c("airport1" = "airport", "airport1_country" = "country"))

names(airports_instudy) <- c("airport", "country", "in_study_2")

pass_od <- left_join(pass_od, airports_instudy, by = c("airport2" = "airport", "airport2_country" = "country"))
pass_od$in_study_all <- pass_od$in_study_1 & pass_od$in_study_2

pass_study_summary <- pass_od %>%
  filter(!is.na(X2018)) %>%
  filter(X2018 > 0) %>%
  group_by(airport2_country, in_study_all) %>%
  summarise(pass_2018 = sum(X2018),
            pass_km_2018 = sum(pass_km_2018))

pass_study_summary$continent <- countrycode(sourcevar = pass_study_summary$airport2_country,
                            origin = "country.name",
                            destination = "continent")
pass_study_summary$continent[pass_study_summary$airport2_country == "Irish Republic"] <- "Europe"
pass_study_summary$continent[pass_study_summary$airport2_country == "Kosovo"] <- "Europe"

pass_study_summary <- pass_study_summary[pass_study_summary$continent == "Europe",]

pass_study_summary <- pivot_wider(pass_study_summary, values_from = c("pass_2018","pass_km_2018"), names_from = "in_study_all")
write.csv(pass_study_summary, "study_area_summary.csv")

```


```{r pass_km_hist, echo=FALSE}

od_hist <- pass_od[pass_od$in_study_all == TRUE,]
od_hist <- od_hist[!is.na(od_hist$X2018),]
od_hist <- od_hist[od_hist$X2018 > 0,]

od_hist <- od_hist[order(od_hist$pass_km_2018, decreasing = TRUE),]
od_hist$cum_pass_km <- cumsum(od_hist$pass_km_2018)
od_hist$cum_pass_km_per <- od_hist$cum_pass_km / max(od_hist$cum_pass_km) * 100

ggplot(od_hist, aes(x = pass_km_2018)) +
  stat_ecdf(geom = "step")

# Group Area Airports Together
lnd <- c("Gatwick","Heathrow","Stansted","London City","Southend","Luton")

od_hist_lnd <- od_hist
od_hist_lnd$airport1[od_hist_lnd$airport1 %in% lnd] <- "London Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% lnd] <- "London Area"

od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Rome (Fiumicino)", "Rome (Ciampino)")] <- "Rome Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Stockholm (Arlanda)", "Stockholm (Skavsta)")] <- "Stockholm Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Warsaw (Chopin)", "Warsaw (Modlin Masovia)")] <- "Warsaw Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Milan (Malpensa)", "Milan (Malpensa)")] <- "Milan Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Berlin (Schonefeld)", "Berlin (Tegel)")] <- "Berlin Area"
od_hist_lnd$airport2[od_hist_lnd$airport2 %in% c("Paris (Charles De Gaulle)", "Paris (Orly)", "Paris (Le Bourget)")] <- "Paris Area"

od_hist_lnd <- od_hist_lnd %>%
  group_by(airport1,airport1_country, airport2, airport2_country) %>%
  summarise(X2018 = sum(X2018),
            pass_km_2018  = sum(pass_km_2018))

od_hist_lnd <- od_hist_lnd[order(od_hist_lnd$pass_km_2018, decreasing = TRUE),]
od_hist_lnd$cum_pass_km <- cumsum(od_hist_lnd$pass_km_2018)
od_hist_lnd$cum_pass_km_per <- od_hist_lnd$cum_pass_km / max(od_hist_lnd$cum_pass_km) * 100

ggplot(od_hist_lnd, aes(x = pass_km_2018)) +
  stat_ecdf(geom = "step")

```
## France
```{r france, echo=FALSE}
od_france <- pass_od
od_france <- od_france[od_france$airport2_country == "France",]
od_france <- od_france[!is.na(od_france$X2018),]
od_france <- od_france[od_france$X2018 > 0,]
sum(od_france$X2018)


# Group Area Airports Together
lnd <- c("Gatwick","Heathrow","Stansted","London City","Southend","Luton")

od_france$airport1[od_france$airport1 %in% lnd] <- "London Area"
od_france$airport2[od_france$airport2 %in% c("Paris (Charles De Gaulle)", "Paris (Orly)", "Paris (Le Bourget)")] <- "Paris Area"

od_france <- od_france %>%
  group_by(airport1,airport1_country, airport2, airport2_country) %>%
  summarise(X2018 = sum(X2018),
            pass_km_2018  = sum(pass_km_2018))

```


